# Generated by Django 5.1.4 on 2025-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
